# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.17.4
 
pipelines:
  branches:
    master:
         - step:
                name : Build and Deploy
                script:
                  - npm install
                  - npm install -g @angular/cli
                  - ng build --configuration production
                artifacts: # defining the artifacts to be passed to each future step.
                  - dist/**
         - step:
                script:
                  - apt-get update
                  - apt-get install -y git
                  - apt-get -qq install git-ftp
                  - ls
                  - cd dist
                  - git config git-ftp.url "ftp://143.198.166.188/var/www/todolist-frontend"
                  - git config git-ftp.user $FTPUSERNAME
                  - git config git-ftp.password $FTP_PASSWORD
                  - git ftp init
                  - git ftp push
                  - echo "Everthing is Okay on Master"
