# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.17.4
definitions:
  steps:
    - step: &Build
        name: Building the application
        caches:
            - node
        script: # Building node service
            - npm install
            - npm install -g @angular/cli
            - ng build -c production
        artifacts: # defining the artifacts to be passed to each future step.
            - dist/**

    - step: &Deploy-Staging
        name: Deploy to production
        deployment: production
        script:
        - pipe: atlassian/scp-deploy:0.3.8
          variables:
            USER: $SSH_USER
            SERVER: $SERVER
            REMOTE_PATH: '~/todolist_frontend/'
            LOCAL_PATH: 'dist/*'

pipelines:
  branches:    
    master:
     - step: *Build
     - step: *Deploy-Staging